version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=base-project
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: domfo/flask-react-base-project:latest
    volumes:
      - app_data:/app/data
      - ./backend/api:/backend/api
    ports:
      - "5005:5000"
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_started
    working_dir: /backend
    environment:
      - ENV_TYPE=prod
    command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -b 0.0.0.0:5000 api:app


  worker:
    image: domfo/flask-react-base-project:latest
    volumes:
      - app_data:/app/data
      - ./backend/api:/backend/api
    depends_on:
      redis:
        condition: service_started
    environment:
      - ENV_TYPE=prod
    command: rq worker --name worker --url redis://redis:6379/0 --with-scheduler
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: domfo/nginx-base:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
volumes:
  postgres_data:
  app_data:
