version: '3.8'

services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    image: domfo/flask-react-base-project:latest
    volumes:
      - app_data:/app/data
      - ./backend/api:/backend/api
    ports:
      - "5005:5000"
    depends_on:
      redis:
        condition: service_started
    working_dir: /backend
    environment:
      - ENV_TYPE=test
      - PYTEST_ADDOPTS="--color=yes"
    command: pytest -vvv -color=yes


  worker:
    image: domfo/flask-react-base-project:latest
    volumes:
      - app_data:/app/data
      - ./backend/api:/backend/api
    depends_on:
      redis:
        condition: service_started
    environment:
      - ENV_TYPE=test
    command: rq worker --url redis://redis:6379/0 --with-scheduler
volumes:
  app_data:
