FROM python:3.10

WORKDIR /backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./backend/requirements.txt .
RUN pip install -r requirements.txt

COPY ./backend /backend

RUN mkdir -p /app/data/uploads /app/data/output 
RUN chmod -R 777 /app/data/uploads /app/data/output
